# Generated by Django 5.0.4 on 2024-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='joinedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
